*Z3950Servers
serverNames

	^ 'Aberdeen University
Academy of Natural Sciences
Acadia University
Amicus
Arizona State University
Athabasca University
Auburn University
Australian National University
Ball State University
Baylor University
Biblioteca de Castilla y Le¦n
Biblioth¦®que nationale du Qu¦©bec
BIBSYS Norway
Binghamton University
Bishop''s University
Boise State University
Boston Athenaeum Library
Boston College Libraries
Boston University
Brandeis University
Brigham Young University
British Columbia Institute of Technology
British Library
Brock University
Brown University
Brunel University
Bryn Mawr/Haverford/Swarthmore Colleges
Bucknell University
Burlington Public Library
California Institute of Technology
California Polytechnic State University, San Luis Obispo
California State Library
California State University, Bakersfield
California State University, East Bay
California State University, Fullerton
California State University, Humboldt
California State University, Long Beach
California State University, Los Angeles
California State University, Monterey Bay
California State University, Northridge
California State University, Pomona
California State University, Sacramento
California State University, San Jose
California State University, San Marcos
California State University, Sonoma
California State University, Stanislaus
Canada Institute for Scientific and Technical Information
Canadian Institute for Historical Microfiche Catalogue
Cape Breton University
Carleton University
Carnegie Mellon University
Centennial College
Center for Research Libraries
Charles Darwin University
Chinese University of Hong Kong
City University of New York
Clark University
Cleveland Public Library
College of the North Atlantic
College of William and Mary
Colorado School of Mines
Colorado State University
Columbia University
Concordia University
COPAC
Cornell University
CSIRO Commonwealth Scientific and Industrial Research Organization
Curtin University of Technology
Dalhousie University
Dallas Theological Seminary
Danish National Library of Science and Medicine
Danish Union Catalog
Dartmouth College
Deakin University
Drake University
Drexel University
Duke University
Dundee University
Durham University
Earth Sciences Information Centre
¦âcole Polytechnique de Montr¦©al
Edinburgh University
Emory University
Fisk University
Flinders University
Florida A&M University
Florida Atlantic University
Florida Gulf Coast University
Florida Institute of Technology
Florida International University
Florida State University
Folger Shakespeare Library
Four Colleges Database (Amherst, Hampshire, Mt. Holyoke, Smith)
George Mason University
Georgetown University
Georgia Tech
German National Library
Getty Center for the History of Art and the Humanities
Glasgow University
Griffith University
Grinnell College
Hong Kong University of Science and Technology
Howard University
Idaho State University
ILLINET
Imperial College London
Indiana State University Consortium
Indiana University
Iowa State University
Israel Union List
James Madison University
Johns Hopkins University
Katholieke Universiteit Leuven
King''s College London
Lakehead University
Laurentian University
Leeds University
Lehigh University
Leicester University
Lewis and Clark College
Library of Congress
Linda Hall Library
London School of Economics
Louisiana State University
Loyola University at New Orleans
Macquarie University Library
Marquette University
Massachusetts Institute of Technology
McGill University
McMaster University
Memorial University of Newfoundland
Michigan State University
Middle Tennessee State University
Middlebury College
MINERVA
Minnesota State University, Mankato Library
Minnesota State University, MSUS
Mississippi State University
Monash University
Montana State University
Morehead State University
Mount Allison University
Murdoch University
Murray State University
Museum of Modern Art
National Agricultural Library
National Library of Australia
National Library of Finland
National Library of New Zealand
National Library of Scotland
National Library of South Africa
National Library of Wales
New College of Florida
New Jersey Institute of Technology
New Jersey State Library
New Mexico State University
New York Public Library
New York State Library
New York University
NOAA Central Library
North Carolina Central University
North Carolina State University
Northern Alberta Institute of Technology
Northern Arizona University
Northern Kentucky University
Northern Territory Library
Northwestern University
Nova Scotia Agricultural College
Nova Scotia College of Art and Design
Novanet
Oakland University
OCLC
OCLC test
Ohio State University
Oklahoma State University
Oklahoma State University, Tulsa
Old Dominion University
Oregon State University
Oxford University
Pennsylvania State University
Pepperdine University
Portland State University
Princeton University
Purdue University
Queen''s University
Queensland University of Technology
Rice University
Royal Historical Society
Rutgers University
San Diego State University
San Francisco State University
State Library of Iowa
State Library of New South Wales
State Library of Queensland
State Library of Victoria
State University of New York, Albany
State University of New York, Stony Brook
Stirling University
Strathclyde University
Syracuse University
Technische Universiteit Delft
Temple University
Texas A&M
Texas State Library & Archives
Texas Tech
Trinity College Dublin
Tri-University Group (Guelph-Waterloo-Wilfred Laurier)
Tulane University
Universit¦© catholique de Louvain
Universit¦© de Moncton
Universit¦© de Montr¦©al
Universit¦© de Sherbrooke
Universit¦© du Qu¦©bec ¦ Montr¦©al
Universit¦© Laval
Universiteit Maastricht
University College Cork
University College London
University of Adelaide
University of Alabama
University of Alabama, Birmingham
University of Alabama, Huntsville
University of Alberta
University of Arizona
University of Arkansas, Fayetteville
University of Auckland
University of Bath
University of Bradford
University of Bridgeport
University of Bristol
University of British Columbia
University of Calgary
University of California, CDL
University of California, Irvine
University of California, Los Angeles
University of California, Riverside
University of Canberra
University of Central Florida
University of Chicago
University of Colorado
University of Connecticut
University of Delaware
University of Dubuque
University of Florida
University of Georgia
University of Hawaii
University of Houston
University of Hull
University of Illinois
University of Iowa
University of Kansas
University of Kentucky
University of London
University of Louisville
University of Manitoba
University of Maryland
University of Massachusetts
University of Miami
University of Michigan
University of Minnesota
University of Missouri
University of Montana
University of Nebraska
University of New South Wales
University of North Carolina, Chapel Hill
University of North Carolina, Greensboro
University of North Florida
University of Northern British Columbia
University of Notre Dame
University of Oklahoma
University of Oregon
University of Pennsylvania
University of Pittsburgh
University of Reading
University of Rochester
University of Saskatchewan
University of Sheffield
University of South Africa
University of South Australia
University of South Carolina
University of South Florida
University of Southampton
University of Southern California
University of Tennessee
University of Texas, Arlington
University of Toronto
University of Utah
University of Victoria
University of Virginia
University of Washington
University of West Florida
University of Western Australia
University of Western Ontario
University of Wisconsin, Madison
University of Wollongong
University of York
University of Z¦ºrich
Vanderbilt University
Victoria University Library
Victoria University of Wellington
Villanova University
Virginia Commonwealth University
Wake Forest University
Waseda University
Washington State Library
Washington State University
Washington University
Wayne State University
Wellcome Trust
Wellesley College
West Chester University
Western Kentucky University
Western Washington University
Wheeling Jesuit University
Williams College
Woods Hole Oceanographic Institution
Yale University
Yeshiva University
York University'